Update e2e-cypress-cloud-run.yml

diff --git a/.github/workflows/e2e-cypress-cloud-run.yml b/.github/workflows/e2e-cypress-cloud-run.yml
--- a/.github/workflows/e2e-cypress-cloud-run.yml
+++ b/.github/workflows/e2e-cypress-cloud-run.yml
@@ -1,4 +1,5 @@
 name: Run Cypress Cloud E2E Tests
+
 on:
   schedule:
     - cron: '30 21,23 * * 0,1,2,3,4'
@@ -62,36 +63,35 @@ jobs:
           else
             echo "env_name=${{ github.event.inputs.environment_name }}" >> $GITHUB_ENV
           fi
+          echo "Github Output: ${{ env.env_name }}"
 
   calculate-containers-count:
     runs-on: ubuntu-latest
-    needs: determine-environment
     outputs:
       default_containers: ${{ steps.set-default.outputs.default_containers }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-    
+
       - name: Install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y jq
-    
+
       - name: Set default containers
         id: set-default
         run: |
-          cloud_record=${{ github.event.inputs.cloud_record }}
-          environment_name=${{ needs.determine-environment.outputs.env_name }}
-    
-          if [[ "$cloud_record" == "true" && ( "$environment_name" == "production" || "$environment_name" == "prod" ) ]]; then
+          cloud_record=${{ github.event.inputs.cloud_record || 'true' }}
+
+          if [[ "$cloud_record" == "true" && ("${{ github.event.inputs.environment_name }}" == "production" || "${{ github.event.inputs.environment_name }}" == "prod") ]]; then
             regions=$(cat cypress/sanity-test-config.json)
             echo "Regions: $regions"
             default_containers=$(echo "$regions" | jq -c '[.regions[] | {workspace_id: .workspace_id, vault_id: .vault_id, display_name: .display_name, data_plane_url: .data_plane_url, workspace_url: .workspace_url, run_create_function_tests: .run_create_function_tests}]')
             echo "default_containers=$default_containers" >> $GITHUB_ENV
-            
+
           elif [[ "$cloud_record" == "true" || "${{ github.event_name }}" == "schedule" ]]; then
             echo "default_containers=[1, 2, 3, 4, 5]" >> $GITHUB_ENV
-    
+
           else
             echo "default_containers=[1]" >> $GITHUB_ENV
 
@@ -107,7 +107,7 @@ jobs:
           echo "Default containers JSON: ${{ needs.calculate-containers-count.outputs.default_containers }}"
           echo "Parsed JSON:"
           echo "${{ needs.calculate-containers-count.outputs.default_containers }}" | jq .
-          
+
       - name: Store env as file
         run: |
           # Fetch the region-specific values from the matrix
@@ -126,12 +126,19 @@ jobs:
               .QUICKSTART_VAULT_ID = $vault_id | 
               .WORKSPACE_URL = $workspace_url | 
               .REGION_DISPLAY_NAME = $display_name' \
-             ./cypress/cypress.env.json > ./cypress/cypress.env.json.tmp && \
-          mv ./cypress/cypress.env.json.tmp ./cypress/cypress.env.json
-          
+             ./cypress/cypress.env.json > ./cypress/cypress.env.json.tmp
+
+          # Ensure that the mv command is executed only if the jq command is successful
+          if [ $? -eq 0 ]; then
+            mv ./cypress/cypress.env.json.tmp ./cypress/cypress.env.json
+          else
+            echo "Failed to update cypress.env.json"
+            exit 1
+          fi
+
       - name: Print updated cypress.env.json
         run: cat cypress/cypress.env.json
-        
+
       - name: Log Matrix Combinations
         run: |
           echo "WORKSPACE_ID: $WORKSPACE_ID (Type: $(echo $WORKSPACE_ID | jq -R 'type'))"
