Update test-workflow.yml

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -3,35 +3,57 @@ name: Test Workflow
 on:
   workflow_dispatch:
     inputs:
-      trigger_failure:
-        description: 'Trigger a failure in the workflow'
+      release_env:
+        description: 'Environment to run the tests' 
+        required: true
+        default: 'sandbox'
+      dryRun:
+        description: 'Set to true to skip actual execution'
         required: true
         default: 'false'
 
+env:
+  release_env: ${{ inputs.release_env }}
+  dry-run: ${{ inputs.dryRun }}
+
 jobs:
-  check-failure:
+  test-logic:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout Current Repository
-        uses: actions/checkout@v3
+      - name: Checkout current repository
+        uses: actions/checkout@v4
 
-      - name: Set Environment Variable
-        run: echo "TRIGGER_FAILURE=${{ github.event.inputs.trigger_failure }}" >> $GITHUB_ENV
+      - name: Set Environment Name
+        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' }}
+        run: |
+          echo "envname=$([[ ${{ env.release_env }} == 'sandbox' ]] && echo 'sandboxv2' || echo 'production')" >> $GITHUB_ENV
+          echo "Environment name set to ${{ env.envname }}"
 
-      - name: Simulate Failure
-        if: ${{ env.TRIGGER_FAILURE == 'true' }}
-        run: exit 1
+      - name: Trigger sanity tests in cypress cloud
+        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' }}
+        run: |
+          echo "TRIGGER_FAILURE=${{ github.event.inputs.trigger_failure }}" >> $GITHUB_ENV
+          echo "Would trigger sanity tests in cypress cloud"
+          echo "Using environment: ${{ env.envname }}"
 
-      - name: Print Message
-        run: echo "Workflow succeeded or failed based on input."
+      - name: Monitor sanity tests of cypress
+        if: ${{ (env.release_env == 'sandbox' || env.release_env == 'prod') && env.dry-run == 'false' && env.TRIGGER_FAILURE == 'true'}}
+        id: sanity-tests-cypress-status
+        run: |
+          echo "Would monitor sanity tests of cypress"
+          echo "Checking status of workflow for repo: ${{ env.studio-ui-repo }}"
+          exit 1
+          
+      - name: Trigger cypress regression tests 
+        if: ${{ github.event.inputs.release_env == 'sandbox' && github.event.inputs['dry-run'] == 'false' && steps.sanity-tests-cypress-status.conclusion == 'success' }}
+        run: |
+          echo "Would trigger regression tests in cypress"
+          echo "Environment name: sandboxv2"
 
-  dependent-job:
-    runs-on: ubuntu-latest
-    needs: check-failure
-    if: ${{ success() }}
-    steps:
-      - name: Checkout Current Repository
-        uses: actions/checkout@v3
 
-      - name: Print Dependent Job Message
-        run: echo "Dependent job ran successfully."
+      - name: Validate status of cypress github workflows
+        if: ${{ github.event.inputs.release_env == 'sandbox' && github.event.inputs['dry-run'] == 'false' }}
+        run: |
+          echo "Would validate status of cypress GitHub workflows"
+          echo "Repo: ${{ env.studio-ui-repo }}"
